---
title: "mzQuality Summary report"
output: 
    html_document:
      toc: true
      toc_float: true
params:
  SE: ""
  project: "mzQuality"
  vendor: "Unknown"

---

<style type="text/css">
div.main-container {
  max-width: 100vw !important;
}
</style>

# About
```{r about, echo=FALSE}
df <- summaryTable(params$SE, params$project, params$vendor)

knitr::kable(
  x = df,
  format = "simple"
)
```

# Heatmap
```{r heatmapPlot, echo = F, out.width="100%"}
se <- params$SE
do.call(tabsetPanel, lapply(assayNames(se), function(x){
  tabPanel(x, ggplotly(heatmapPlot(se, assay = x)))
}))
```

# Aliquot Plot
```{r sample_area, echo=FALSE, out.width="100%"}
se <- params$SE

do.call(fluidRow, lapply(assayNames(se), function(assay){
  div(
    h2(assay),
    do.call(tabsetPanel, lapply(unique(se$Batch), function(x){
      
      p <- ggplotly(aliquotPlot(se, x, assay), dynamicTicks = TRUE, height = 540)
      tabPanel(paste("Batch", x), p, )
    }))
  )
})
)
```

# Batch Correction
```{r batch, echo=FALSE, out.width="100%"}
se <- params$SE
ggplotly(batchCorrectionPlot(se[, se$Type == metadata(se)$QC]), dynamicTicks = TRUE)
```

# PCA Plot
```{r pca, echo=FALSE, out.width="100%"}
se <- params$SE
ggplotly(pcaPlot(se[, se$Type %in% c("SAMPLE", "SQC", "LQC")]), dynamicTicks = TRUE)
```

# QC Plot
```{r badqc, echo=FALSE, out.width="100%", warning=FALSE}
exp <- aliquotFilter(params$SE, Type = metadata(params$SE)$QC)
ggplotly(violinPlot(exp))
```

# Coefficient Variation
```{r cv, echo=FALSE, out.width="100%"}
se <- params$SE
if (metadata(se)$hasIS) {
  exp <- aliquotFilter(se, Type = metadata(se)$QC)
  ggplotly(coefVariationPlot(exp), dynamicTicks = TRUE)
}

```

# RSDQC
```{r heatmap, echo=FALSE, out.width="100%"}
se <- params$SE
tryCatch({
  if (metadata(se)$hasIS) rsdqcPlot(params$SE)
}, error = function(x){
  
})

```


